/**
 * PAD-320 — the conversion backlog for the rendered-text guard.
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST.
 *
 * Every entry is a file that still asserts on rendered copy and has not been converted
 * yet. An entry is a debt with a number on it, not permission. Adding one is a decision
 * with a name on it — say so in the commit message — and it is never the way to make a
 * red go away.
 *
 * `max` is a ratchet and the guard enforces it in BOTH directions:
 *   more than `max`  -> a new rendered-text assertion was added; fix the assertion
 *   fewer than `max` -> lower `max` to the number the failure message gives you
 *   zero             -> delete the entry
 *
 * The downward direction is the one that matters: headroom left after a partial
 * conversion lets new violations back in under the old ceiling while the guard reports
 * success, which is how a ratchet dies.
 *
 * GENERATED BY THE GUARD ITSELF — never by hand, never by a separate script:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * 52 assertions across 23 files. Out of scope by decision and absent
 * here: `getByRole(…, { name })` with a typed name (its own list, e2e-role-name-backlog.ts,
 * PAD-342), the bilingual `/delete|eliminar/i` alternation (PAD-322), files whose subject
 * IS the text (SUBJECT_ALLOWLIST), and literals matching no locale value (test-created data).
 */

export interface BacklogEntry {
  /** Display name: `pw:<path under apps/web/e2e>` or `mz:<path under .maestro>`. */
  file: string;
  /** Exact number of convertible assertions remaining in the file. */
  max: number;
  /** What is in there, so a reader sees the size of the debt without opening it. */
  reason: string;
}

export const BACKLOG: readonly BacklogEntry[] = [
  { file: "pw:settings/notification-engine-settings.spec.ts", max: 14, reason: "14 en UI strings, e.g. '^automatic notifications$', '^group 1$'" },
  { file: "mz:flows/34-player-removal.yaml", max: 6, reason: "6 en UI strings, e.g. 'Attendance records: .*', 'Attendance records: 0'" },
  { file: "pw:dashboard/student-dashboard-home.spec.ts", max: 4, reason: "4 en UI strings, e.g. 'NEEDS YOU', 'NEEDS YOU · \\d+'" },
  { file: "pw:evaluation-tools/evaluation-persist.spec.ts", max: 3, reason: "3 en UI strings, e.g. 'no evaluations yet'" },
  { file: "pw:import-history/import-history.spec.ts", max: 3, reason: "3 en UI strings, e.g. 'are you sure', 'successfully reverted'" },
  { file: "mz:flows/04-attendance.yaml", max: 2, reason: "2 en UI strings, e.g. 'Attendance saved', 'Attended'" },
  { file: "pw:exercise-management/tactical-board.spec.ts", max: 2, reason: "2 en UI strings, e.g. 'draw the balls path', 'tap a piece to select it'" },
  { file: "pw:notification-engine/cancellation-deadline.spec.ts", max: 2, reason: "2 en UI strings, e.g. '^automatic notifications$', '^cancellation deadline$'" },
  { file: "pw:settings/season-definition.spec.ts", max: 2, reason: "2 en UI strings, e.g. 'does not exist in that month', 'season:'" },
  { file: "mz:flows/13-student-availability.yaml", max: 1, reason: "1 en UI string, e.g. 'No blockers yet'" },
  { file: "mz:flows/43-tutorials-understand-invites.yaml", max: 1, reason: "1 en UI string, e.g. 'first batch'" },
  { file: "pw:availability/unavailable-student-notifications.spec.ts", max: 1, reason: "1 en UI string, e.g. 'notification'" },
  { file: "pw:clubs/courts.spec.ts", max: 1, reason: "1 en UI string, e.g. 'already exists'" },
  { file: "pw:messaging/conversation-day-label.spec.ts", max: 1, reason: "1 en UI string, e.g. '^Yesterday$'" },
  { file: "pw:player-management/add-player.spec.ts", max: 1, reason: "1 en UI string, e.g. 'strengths.*weaknesses'" },
  { file: "pw:player-management/create-player-level-dropdown.spec.ts", max: 1, reason: "1 en UI string, e.g. 'no levels defined yet'" },
  { file: "pw:player-management/delete-player.spec.ts", max: 1, reason: "1 en UI string, e.g. 'are you sure'" },
  { file: "pw:player-management/ticket-pad-105-coach-no-username.spec.ts", max: 1, reason: "1 both UI string, e.g. '^username$'" },
  { file: "pw:players/add-to-classes.spec.ts", max: 1, reason: "1 en UI string, e.g. 'no classes this week'" },
  { file: "pw:schedule-calendar/class-delete-confirm.spec.ts", max: 1, reason: "1 en UI string, e.g. 'delete this class\\?'" },
  { file: "pw:schedule-calendar/mobile-day-view.spec.ts", max: 1, reason: "1 en UI string, e.g. '5 classes'" },
  { file: "pw:schedule-calendar/participant-count-effective.spec.ts", max: 1, reason: "1 en UI string, e.g. '^capacity$'" },
  { file: "pw:settings/temp-id-delete-after-save.spec.ts", max: 1, reason: "1 en UI string, e.g. 'strengths.*weaknesses'" },
] as const;
