/**
 * PAD-510 (B-282) — the guard: no Playwright locator climbs the page (`xpath=ancestor::…`,
 * `xpath=..`, `xpath=parent::…`, `locator("..")`). See e2e-dom-climb-scan.ts for why.
 *
 * Same shape as the rendered-text guard (PAD-320): GREEN on landing, every file that still climbs is
 * in DOM_CLIMB_BACKLOG with an exact count, and the count is a ratchet enforced in both directions.
 * The scanner is validated before it is trusted ("the scanner catches climbs").
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { DOM_CLIMB_BACKLOG } from "./e2e-dom-climb-backlog";
import { scanClimbs, type Climb } from "./e2e-dom-climb-scan";

const HERE = dirname(fileURLToPath(import.meta.url));
const E2E_DIR = resolve(HERE, "../../e2e");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (entry.endsWith(".ts")) out.push(full);
  }
  return out.sort();
}

const climbs: Climb[] = walk(E2E_DIR).flatMap((f) =>
  scanClimbs(`pw:${relative(E2E_DIR, f)}`, readFileSync(f, "utf8")),
);
const countsByFile = climbs.reduce<Record<string, number>>((acc, c) => {
  acc[c.file] = (acc[c.file] ?? 0) + 1;
  return acc;
}, {});

/**
 * The backlog file, written by this guard and nothing else (one instrument, not two):
 *   UPDATE_E2E_CLIMB_BACKLOG=1 npx vitest run src/lib/e2e-dom-climb.test.ts
 */
function renderBacklog(): string {
  const entries = Object.entries(countsByFile).sort(([a], [b]) => a.localeCompare(b));
  const total = entries.reduce((n, [, c]) => n + c, 0);
  const rows = entries.map(([file, max]) => {
    const lines = climbs.filter((c) => c.file === file).map((c) => c.line).join(", ");
    return `  { file: ${JSON.stringify(file)}, max: ${max}, reason: ${JSON.stringify(`line ${lines}`)} },`;
  });
  return `/**
 * PAD-510 (B-282) — the conversion backlog for the DOM-climb guard (e2e-dom-climb.test.ts).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST. Every entry is a file whose locators still climb the
 * page; an entry is a debt with a number on it, and adding one is never the way to make a red go
 * away. \`max\` is a ratchet enforced in BOTH directions: more than \`max\` -> fix the new climb; fewer
 * -> lower \`max\` to the number the failure gives you; zero -> delete the entry.
 *
 * GENERATED BY THE GUARD ITSELF — never by hand, never by a separate script:
 *   UPDATE_E2E_CLIMB_BACKLOG=1 npx vitest run src/lib/e2e-dom-climb.test.ts
 *
 * ${total} climbs across ${entries.length} files.
 */

export interface ClimbBacklogEntry {
  /** Display name: \`pw:<path under apps/web/e2e>\`. */
  file: string;
  /** Exact number of climbs remaining in the file. */
  max: number;
  /** Where they are. */
  reason: string;
}

export const DOM_CLIMB_BACKLOG: readonly ClimbBacklogEntry[] = [
${rows.join("\n")}
] as const;
`;
}

if (process.env.UPDATE_E2E_CLIMB_BACKLOG === "1") {
  writeFileSync(resolve(HERE, "e2e-dom-climb-backlog.ts"), renderBacklog());
}

describe("the scanner catches climbs", () => {
  // Without this block the guard can pass by matching nothing at all.
  it("finds each kind of climb, once per occurrence", () => {
    const source = [
      `page.getByText("x").locator("xpath=ancestor::div[1]")`,
      `row.locator("xpath=..")`,
      `row.locator('xpath=parent::li')`,
      `cell.locator("..")`,
      `a.locator("xpath=ancestor::div").locator("xpath=ancestor::section")`,
    ].join("\n");
    expect(scanClimbs("pw:x.spec.ts", source).map((c) => c.line)).toEqual([1, 2, 3, 4, 5, 5]);
  });

  it("leaves test ids, roles and child locators alone", () => {
    const source = [
      `page.getByTestId("engine-toggle")`,
      `page.getByRole("switch", { name: "x" })`,
      `row.locator("xpath=./span")`,
      `row.locator("..span")`,
      `// "ancestor" in a comment, not a locator`,
    ].join("\n");
    expect(scanClimbs("pw:x.spec.ts", source)).toEqual([]);
  });

  it("finds the climbs that are really in the specs (a scan of the tree that matched nothing would be green forever)", () => {
    expect(climbs.length).toBe(DOM_CLIMB_BACKLOG.reduce((n, e) => n + e.max, 0));
  });
});

describe("no Playwright locator climbs the page (PAD-510, B-282)", () => {
  it("no file outside the backlog has a climb", () => {
    const listed = new Set(DOM_CLIMB_BACKLOG.map((e) => e.file));
    const unlisted = climbs.filter((c) => !listed.has(c.file)).map((c) => `${c.file}:${c.line} ${c.match}`);
    expect(unlisted, "find the element by test id or role instead").toEqual([]);
  });

  it.each(DOM_CLIMB_BACKLOG.map((e) => [e.file, e.max] as const))("%s has exactly %i (the ratchet only goes down)", (file, max) => {
    expect(countsByFile[file] ?? 0, "lower or delete this entry with UPDATE_E2E_CLIMB_BACKLOG=1").toBe(max);
  });
});
