/**
 * PAD-320 — the conversion backlog for the rendered-text guard.
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST.
 *
 * Every entry is a file that still asserts on rendered copy and has not been converted
 * yet. An entry is a debt with a number on it, not permission. Adding one is a decision
 * with a name on it — say so in the commit message — and it is never the way to make a
 * red go away.
 *
 * `max` is a ratchet and the guard enforces it in BOTH directions:
 *   more than `max`  -> a new rendered-text assertion was added; fix the assertion
 *   fewer than `max` -> lower `max` to the number the failure message gives you
 *   zero             -> delete the entry
 *
 * The downward direction is the one that matters: headroom left after a partial
 * conversion lets new violations back in under the old ceiling while the guard reports
 * success, which is how a ratchet dies.
 *
 * GENERATED BY THE GUARD ITSELF — never by hand, never by a separate script:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * 38 assertions across 24 files. Out of scope by decision and absent
 * here: `getByRole(…, { name })` (182 — R-013 prefers role locators; PAD-342 decides),
 * the bilingual `/delete|eliminar/i` alternation, files whose subject IS the text
 * (SUBJECT_ALLOWLIST), and literals matching no locale value (test-created data).
 */

export interface BacklogEntry {
  /** Display name: `pw:<path under apps/web/e2e>` or `mz:<path under .maestro>`. */
  file: string;
  /** Exact number of convertible assertions remaining in the file. */
  max: number;
  /** What is in there, so a reader sees the size of the debt without opening it. */
  reason: string;
}

export const BACKLOG: readonly BacklogEntry[] = [
  { file: "pw:availability/unavailable-student-notifications.spec.ts", max: 4, reason: "4 en UI strings, e.g. 'class created', 'unavailable'" },
  { file: "mz:flows/04-attendance.yaml", max: 2, reason: "2 en UI strings, e.g. 'Attendance saved', 'Attended'" },
  { file: "mz:flows/34-player-removal.yaml", max: 2, reason: "2 en UI strings, e.g. 'Delete Player', 'Disconnect'" },
  { file: "pw:schedule-calendar/class-overlap-warning.spec.ts", max: 2, reason: "2 en UI strings, e.g. 'class created'" },
  { file: "mz:flows/13-student-availability.yaml", max: 1, reason: "1 en UI string, e.g. 'No blockers yet'" },
  { file: "mz:flows/43-tutorials-understand-invites.yaml", max: 1, reason: "1 en UI string, e.g. 'first batch'" },
  { file: "pw:evaluation-tools/evaluation-persist.spec.ts", max: 1, reason: "1 en UI string, e.g. 'evaluation saved'" },
  { file: "pw:messaging/direct-messages.spec.ts", max: 1, reason: "1 en UI string, e.g. 'Message deleted'" },
  { file: "pw:notification-engine/class-cancellation-notification.spec.ts", max: 1, reason: "1 en UI string, e.g. 'Class deleted'" },
  { file: "pw:notification-engine/manual-notify-selection.spec.ts", max: 1, reason: "1 en UI string, e.g. 'notify students'" },
  { file: "pw:notification-engine/standing-waitlist-expired.spec.ts", max: 1, reason: "1 en UI string, e.g. 'auto-invite engine'" },
  { file: "pw:player-management/level-formatting.spec.ts", max: 1, reason: "1 en UI string, e.g. 'Select level'" },
  { file: "pw:players/set-player-level.spec.ts", max: 1, reason: "1 en UI string, e.g. 'Intermediate'" },
  { file: "pw:schedule-calendar/mobile-week-view.spec.ts", max: 1, reason: "1 en UI string, e.g. 'No classes scheduled'" },
  { file: "pw:settings/theme-dark-mode.spec.ts", max: 1, reason: "1 en UI string, e.g. 'dark'" },
  { file: "pw:settings/ticket-pad-109-standing-waitlist-search.spec.ts", max: 1, reason: "1 en UI string, e.g. 'auto-invite engine'" },
] as const;
