/**
 * PAD-510 (B-282) — the conversion backlog for the DOM-climb guard (e2e-dom-climb.test.ts).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST. Every entry is a file whose locators still climb the
 * page; an entry is a debt with a number on it, and adding one is never the way to make a red go
 * away. `max` is a ratchet enforced in BOTH directions: more than `max` -> fix the new climb; fewer
 * -> lower `max` to the number the failure gives you; zero -> delete the entry.
 *
 * GENERATED BY THE GUARD ITSELF — never by hand, never by a separate script:
 *   UPDATE_E2E_CLIMB_BACKLOG=1 npx vitest run src/lib/e2e-dom-climb.test.ts
 *
 * 5 climbs across 4 files.
 */

export interface ClimbBacklogEntry {
  /** Display name: `pw:<path under apps/web/e2e>`. */
  file: string;
  /** Exact number of climbs remaining in the file. */
  max: number;
  /** Where they are. */
  reason: string;
}

export const DOM_CLIMB_BACKLOG: readonly ClimbBacklogEntry[] = [
  { file: "pw:notification-engine/cancellation-deadline.spec.ts", max: 1, reason: "line 53" },
  { file: "pw:schedule-calendar/participant-count-effective.spec.ts", max: 1, reason: "line 169" },
  { file: "pw:settings/notification-engine-settings.spec.ts", max: 2, reason: "line 165, 224" },
  { file: "pw:settings/ticket-pad-109-standing-waitlist-search.spec.ts", max: 1, reason: "line 75" },
] as const;
