/**
 * PAD-342 — the conversion backlog for TYPED role names (R-013 as amended).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST — the same contract as
 * e2e-rendered-text-backlog.ts: `max` is a ratchet enforced in both directions, an
 * entry is a debt with a number on it, and adding one is never the way to make a red
 * go away. The fix is `name: ui("<locale key>")` from e2e/helpers/i18n.ts, which the
 * scanner cannot see because it is a call, not a literal.
 *
 * GENERATED BY THE GUARD ITSELF, in the same run that writes the text backlog:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * 263 typed role names across 60 files. Absent here: names given as a
 * call or an identifier (resolved, or test data by construction), literals matching no
 * locale value, and bilingual alternations (PAD-322).
 */

export interface RoleBacklogEntry {
  /** Display name: `pw:<path under apps/web/e2e>`. */
  file: string;
  /** Exact number of typed role names remaining in the file. */
  max: number;
  /** What is in there. */
  reason: string;
}

export const ROLE_BACKLOG: readonly RoleBacklogEntry[] = [
  { file: "pw:exercise-management/tactical-board.spec.ts", max: 25, reason: "25 both+en role names, e.g. 'add players', 'add step'" },
  { file: "pw:settings/notification-engine-settings.spec.ts", max: 14, reason: "14 en role names, e.g. 'add group', 'add rule'" },
  { file: "pw:landing/landing-page.spec.ts", max: 13, reason: "13 pt role names, e.g. 'calendário', 'entrar'" },
  { file: "pw:availability/student-blockers.spec.ts", max: 11, reason: "11 en role names, e.g. 'Availability', 'add blocker'" },
  { file: "pw:availability/unavailable-student-notifications.spec.ts", max: 11, reason: "11 en role names, e.g. 'add blocker', 'all'" },
  { file: "pw:import-history/import-history.spec.ts", max: 8, reason: "8 en role names, e.g. 'cancel', 'confirm'" },
  { file: "pw:notification-engine/reminder-flow.spec.ts", max: 7, reason: "7 en role names, e.g. 'cancel', 'notify'" },
  { file: "pw:notification-engine/semi-auto-approval.spec.ts", max: 7, reason: "7 en role names, e.g. 'absent', 'confirm'" },
  { file: "pw:calendar/season-end-no-season.spec.ts", max: 6, reason: "6 en role names, e.g. 'create class', 'new class'" },
  { file: "pw:exercise-management/exercise-crud.spec.ts", max: 6, reason: "6 en role names, e.g. 'delete', 'delete exercise'" },
  { file: "pw:loading-states/ticket-pad-24-loading-states.spec.ts", max: 6, reason: "6 en role names, e.g. 'Edit', 'create class'" },
  { file: "pw:notification-engine/class-cancellation-notification.spec.ts", max: 6, reason: "6 en role names, e.g. 'add class', 'all'" },
  { file: "pw:player-management/ticket-pad-105-coach-no-username.spec.ts", max: 6, reason: "6 en role names, e.g. 'add player', 'create player'" },
  { file: "pw:schedule-calendar/class-delete-confirm.spec.ts", max: 6, reason: "6 en role names, e.g. 'add class', 'cancel'" },
  { file: "pw:schedule-calendar/class-deletion.spec.ts", max: 6, reason: "6 en role names, e.g. 'add class', 'create class'" },
  { file: "pw:settings/coach-levels-ordering-hint.spec.ts", max: 6, reason: "6 en role names, e.g. 'add level', 'coach levels'" },
  { file: "pw:settings/season-definition.spec.ts", max: 6, reason: "6 en role names, e.g. 'calendar', 'create class'" },
  { file: "pw:settings/student-settings-scope.spec.ts", max: 6, reason: "6 en role names, e.g. 'coach levels', 'evaluation categories'" },
  { file: "pw:settings/temp-id-delete-after-save.spec.ts", max: 6, reason: "6 en role names, e.g. 'add level', 'add strength'" },
  { file: "pw:player-management/create-player-level-dropdown.spec.ts", max: 5, reason: "5 en role names, e.g. 'Beginner', 'Intermediate'" },
  { file: "pw:players/claim-existing-account.spec.ts", max: 5, reason: "5 en role names, e.g. 'Edit', 'Intermediate'" },
  { file: "pw:evaluation-tools/player-notes.spec.ts", max: 4, reason: "4 en role names, e.g. 'Edit', 'add strength'" },
  { file: "pw:player-management/duplicate-name-warning.spec.ts", max: 4, reason: "4 en role names, e.g. 'add player', 'create player'" },
  { file: "pw:player-management/duplicate-username-warning.spec.ts", max: 4, reason: "4 en role names, e.g. 'add player', 'create player'" },
  { file: "pw:player-management/players-sort-filter-alerts.spec.ts", max: 4, reason: "4 en role names, e.g. 'Level High-Low', 'Name Z-A'" },
  { file: "pw:players/set-player-level.spec.ts", max: 4, reason: "4 en role names, e.g. 'Edit', 'Intermediate'" },
  { file: "pw:schedule-calendar/class-overlap-warning.spec.ts", max: 4, reason: "4 en role names, e.g. 'create class', 'proceed anyway'" },
  { file: "pw:settings/coach-settings.spec.ts", max: 4, reason: "4 en role names, e.g. 'calendar', 'preferences'" },
  { file: "pw:availability/mobile-layout.spec.ts", max: 3, reason: "3 pt role names, e.g. 'Adicionar bloqueio', 'Disponibilidade'" },
  { file: "pw:clubs/coach-invitation.spec.ts", max: 3, reason: "3 en role names, e.g. 'club', 'invite a coach'" },
  { file: "pw:clubs/courts.spec.ts", max: 3, reason: "3 en role names, e.g. 'club', 'create class'" },
  { file: "pw:evaluation-tools/evaluation-persist.spec.ts", max: 3, reason: "3 en role names, e.g. 'add evaluation', 'save evaluation'" },
  { file: "pw:exercise-management/exercise-groups.spec.ts", max: 3, reason: "3 en role names, e.g. 'create group', 'groups'" },
  { file: "pw:messaging/direct-messages.spec.ts", max: 3, reason: "3 en role names, e.g. 'delete', 'edit'" },
  { file: "pw:player-management/player-side-both.spec.ts", max: 3, reason: "3 en role names, e.g. 'Both', 'Edit'" },
  { file: "pw:player-management/search-edit-player.spec.ts", max: 3, reason: "3 en role names, e.g. 'Edit', 'Left'" },
  { file: "pw:schedule-calendar/class-date-prepopulate.spec.ts", max: 3, reason: "3 en role names, e.g. 'add class', 'next week'" },
  { file: "pw:settings/profile-persistence.spec.ts", max: 3, reason: "3 en role names, e.g. 'profile', 'save changes'" },
  { file: "pw:evaluation-tools/eval-categories.spec.ts", max: 2, reason: "2 en role names, e.g. 'add evaluation'" },
  { file: "pw:layout/mobile-bottom-nav.spec.ts", max: 2, reason: "2 pt role names, e.g. 'definições'" },
  { file: "pw:notification-engine/cancellation-deadline.spec.ts", max: 2, reason: "2 en role names, e.g. 'reminders', 'restrictions'" },
  { file: "pw:player-management/activation-link-secret.spec.ts", max: 2, reason: "2 en role names, e.g. 'add player', 'create player'" },
  { file: "pw:player-management/add-player.spec.ts", max: 2, reason: "2 en role names, e.g. 'add player', 'create player'" },
  { file: "pw:player-management/level-formatting.spec.ts", max: 2, reason: "2 en role names, e.g. 'Beginner', 'add player'" },
  { file: "pw:player-management/player-invite-completion.spec.ts", max: 2, reason: "2 en role names, e.g. 'add player', 'invite'" },
  { file: "pw:players/add-to-classes.spec.ts", max: 2, reason: "2 en role names, e.g. 'add to classes', 'next week'" },
  { file: "pw:schedule-calendar/attendance-save.spec.ts", max: 2, reason: "2 en role names, e.g. 'confirm', 'present'" },
  { file: "pw:settings/theme-dark-mode.spec.ts", max: 2, reason: "2 en role names, e.g. 'preferences'" },
  { file: "pw:settings/ticket-pad-109-standing-waitlist-search.spec.ts", max: 2, reason: "2 en role names, e.g. 'add to waiting list', 'standing waiting list'" },
  { file: "pw:dashboard/student-dashboard-kpi.spec.ts", max: 1, reason: "1 en role name, e.g. 'invites'" },
  { file: "pw:messaging/messageable-roster.spec.ts", max: 1, reason: "1 en role name, e.g. 'new conversation'" },
  { file: "pw:notification-engine/manual-notify-selection.spec.ts", max: 1, reason: "1 en role name, e.g. 'notify'" },
  { file: "pw:notification-engine/notification-config.spec.ts", max: 1, reason: "1 en role name, e.g. 'notify'" },
  { file: "pw:notification-engine/standing-waitlist-expired.spec.ts", max: 1, reason: "1 en role name, e.g. 'standing waiting list'" },
  { file: "pw:player-management/delete-player.spec.ts", max: 1, reason: "1 en role name, e.g. 'delete player'" },
  { file: "pw:schedule-calendar/class-management.spec.ts", max: 1, reason: "1 en role name, e.g. 'delete class'" },
  { file: "pw:schedule-calendar/daily-schedule.spec.ts", max: 1, reason: "1 en role name, e.g. 'next week'" },
  { file: "pw:schedule-calendar/mobile-weekly-order.spec.ts", max: 1, reason: "1 en role name, e.g. 'next week'" },
  { file: "pw:schedule-calendar/recurring-occurrence-delete.spec.ts", max: 1, reason: "1 en role name, e.g. 'delete class'" },
  { file: "pw:schedule-calendar/slot-drag-select.spec.ts", max: 1, reason: "1 en role name, e.g. 'next week'" },
] as const;
