/**
 * PAD-322 — the conversion backlog for BILINGUAL ALTERNATIONS (`/delete|eliminar/i`).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST — the same contract as the text and role
 * backlogs: `max` is a ratchet enforced in both directions, an entry is a debt with a
 * number on it, and adding one is never the way to make a red go away. An alternation
 * is counted when at least one half resolves to a locale value; the fix is the same
 * resolved shape as a role name — `ui("<locale key>")` from e2e/helpers/i18n.ts — which
 * the scanner cannot see because it is a call, not a literal.
 *
 * GENERATED BY THE GUARD ITSELF, in the same run that writes the other two lists:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * 123 bilingual alternations across 49 files. Absent here: an escaped
 * bar (`\|`), alternations whose halves resolve to nothing, and subject files.
 */

export interface AltBacklogEntry {
  /** Display name: `pw:<path under apps/web/e2e>`. */
  file: string;
  /** Exact number of bilingual alternations remaining in the file. */
  max: number;
  /** What is in there. */
  reason: string;
}

export const ALT_BACKLOG: readonly AltBacklogEntry[] = [
  { file: "pw:notification-engine/reminder-flow.spec.ts", max: 12, reason: "12 bilingual alternations, e.g. /500|internal server error|something went wrong/, /add|confirm|save/" },
  { file: "pw:notification-engine/eligibility-manual-add.spec.ts", max: 8, reason: "8 bilingual alternations, e.g. /1 level above this class|1 nível acima desta aula/, /^(all|todos)$/" },
  { file: "pw:clubs/coach-invitation.spec.ts", max: 7, reason: "7 bilingual alternations, e.g. /^(name|nome)$/, /^(password|palavra-passe)$/" },
  { file: "pw:exercise-management/tactical-board.spec.ts", max: 6, reason: "6 bilingual alternations, e.g. /create exercise|save/, /save|update/" },
  { file: "pw:notification-engine/waiting-list-offer.spec.ts", max: 6, reason: "6 bilingual alternations, e.g. /^declined$|^recusado$/, /^no$|^não$/" },
  { file: "pw:players/player-removal.spec.ts", max: 6, reason: "6 bilingual alternations, e.g. /^(cancel|cancelar)$/, /^(delete player|eliminar jogador)$/" },
  { file: "pw:exercise-management/exercise-crud.spec.ts", max: 5, reason: "5 bilingual alternations, e.g. /all types|type/, /create exercise|save/" },
  { file: "pw:player-management/player-invite-completion.spec.ts", max: 5, reason: "5 bilingual alternations, e.g. /^(password|palavra-passe)$/, /^(username|nome de utilizador)$/" },
  { file: "pw:availability/unavailable-student-notifications.spec.ts", max: 4, reason: "4 bilingual alternations, e.g. /add class|new class/, /beginner academy|private/" },
  { file: "pw:schedule-calendar/class-management.spec.ts", max: 4, reason: "4 bilingual alternations, e.g. /add class|new class|\\+/, /beginner academy|private/" },
  { file: "pw:settings/evaluation-category-delete.spec.ts", max: 4, reason: "4 bilingual alternations, e.g. /^(add category|adicionar categoria)$/, /^(name|nome)$/" },
  { file: "pw:attendance/presences-validation.spec.ts", max: 3, reason: "3 bilingual alternations, e.g. /^(undo|anular)$/, /previous week|semana anterior/" },
  { file: "pw:notification-engine/standing-waitlist-expired.spec.ts", max: 3, reason: "3 bilingual alternations, e.g. /expired|expirado/, /remove|delete/" },
  { file: "pw:player-management/delete-player.spec.ts", max: 3, reason: "3 bilingual alternations, e.g. /^(cancel|cancelar)$/, /^(delete player|disconnect|eliminar jogador|desassociar)$/" },
  { file: "pw:schedule-calendar/class-overlap-warning.spec.ts", max: 3, reason: "3 bilingual alternations, e.g. /add class|new class/, /beginner academy|private/" },
  { file: "pw:attendance/absence-history.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /faltas|absences/, /presenças|attendance/" },
  { file: "pw:dashboard/needs-you-deep-links.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /Notificar alunos|Notify students/, /convidar|invite/" },
  { file: "pw:dashboard/student-dashboard-home.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /^(Dashboard|Painel)$/, /open|abrir/" },
  { file: "pw:helpers/calendar-navigation.ts", max: 2, reason: "2 bilingual alternations, e.g. /next week|semana seguinte/, /previous week|semana anterior/" },
  { file: "pw:messaging/message-by-username.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /new conversation|nova conversa/, /no user with that username|não existe nenhum utilizador/" },
  { file: "pw:messaging/unknown-sender-banner.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /new conversation|nova conversa/, /unblock|desbloquear/" },
  { file: "pw:player-management/duplicate-name-warning.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /already have a player.*this name|possible duplicate|duplicate name/" },
  { file: "pw:player-management/search-edit-player.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /doesnt have an account|can register|invite/, /error|failed/" },
  { file: "pw:player-management/ticket-pad-105-coach-no-username.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /^(username|nome de utilizador)$/, /username|nome de utilizador/" },
  { file: "pw:settings/request-alerts-optout.spec.ts", max: 2, reason: "2 bilingual alternations, e.g. /^(preferences|preferências)$/" },
  { file: "pw:attendance/attendance-history.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /participants|attendance/" },
  { file: "pw:availability/student-blockers.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /won?t receive|auto[- ]?invitation|unavailable/" },
  { file: "pw:calendar/season-end-no-season.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /new class|add class/" },
  { file: "pw:class-requests/class-request-counter-proposal.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /Aula marcada|Class booked/" },
  { file: "pw:clubs/courts.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /new class|add class/" },
  { file: "pw:dashboard/validation-count.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /review|rever/" },
  { file: "pw:evaluation-tools/eval-categories.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /save|submit/" },
  { file: "pw:loading-states/ticket-pad-24-loading-states.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /add class|new class|\\+/" },
  { file: "pw:messaging/conversation-open-anchor.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /scroll to bottom|ir para o fim|new messages|novas mensagens/" },
  { file: "pw:messaging/conversation-paging.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /scroll to bottom|ir para o fim|new messages|novas mensagens/" },
  { file: "pw:notification-engine/cancel-attendance-class-view.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /error|failed|went wrong/" },
  { file: "pw:notification-engine/class-cancellation-notification.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /beginner academy|private/" },
  { file: "pw:notification-engine/eligibility-class-override.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /^(save|guardar)$/" },
  { file: "pw:notification-engine/notification-config.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /send|notify|invite/" },
  { file: "pw:notification-engine/semi-auto-approval.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /mark attendance|edit attendance/" },
  { file: "pw:player-management/player-side-both.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /error|failed/" },
  { file: "pw:player-management/players-sort-filter-alerts.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /clear|remove|reset|show all/" },
  { file: "pw:schedule-calendar/attendance-save.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /mark attendance|edit attendance/" },
  { file: "pw:schedule-calendar/class-delete-confirm.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /beginner academy|private/" },
  { file: "pw:schedule-calendar/class-deletion.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /beginner academy|private/" },
  { file: "pw:settings/my-connections.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /delete account|eliminar conta/" },
  { file: "pw:settings/season-definition.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /new class|add class/" },
  { file: "pw:settings/student-notification-blocks.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /injustificada|unjustified/" },
  { file: "pw:settings/tutorials-understand-invites.spec.ts", max: 1, reason: "1 bilingual alternation, e.g. /1 level above this class|1 nível acima desta aula/" },
] as const;
