/**
 * PAD-320 — the guard: no E2E assertion matches on rendered copy.
 *
 * The web app renders pt and the mobile app renders en, so an assertion on visible
 * text passes or fails depending on which language the run came up in, and breaks
 * whenever a translator touches the string. Assert on `data-testid` and ids instead.
 *
 * This file is GREEN on landing. Every file that still has such an assertion is in
 * BACKLOG with an exact count, and each conversion slice lowers or deletes its entry.
 * If you are tempted to make this suite red to "show the work", don't: a red that is
 * expected teaches everyone to ignore reds, and a guard people ignore is worse than
 * no guard because it looks like coverage. The red belongs in the backlog, not in CI.
 *
 * The scanner is validated before it is trusted (see "the scanner catches things"):
 * a scan that silently matches nothing is green forever, which is the most flattering
 * possible way to learn nothing.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { BACKLOG } from "./e2e-rendered-text-backlog";
import { ROLE_BACKLOG } from "./e2e-role-name-backlog";
import { ALT_BACKLOG } from "./e2e-bilingual-backlog";
import {
  classify,
  localeValues,
  scanMaestro,
  scanPlaywright,
  scanAlternations,
  scanRoleNames,
  type Locales,
  type Violation,
} from "./e2e-rendered-text-scan";

const HERE = dirname(fileURLToPath(import.meta.url));
const E2E_DIR = resolve(HERE, "../../e2e");
const MAESTRO_DIR = resolve(HERE, "../../../mobile/.maestro");
const LOCALES_DIR = resolve(HERE, "../../../../src/locales");

function walk(dir: string, ext: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, ext));
    else if (entry.endsWith(ext)) out.push(full);
  }
  return out.sort();
}

function loadLocale(lang: string, minLength: number): Set<string> {
  const dir = join(LOCALES_DIR, lang);
  const values = new Set<string>();
  for (const file of walk(dir, ".json")) {
    localeValues(JSON.parse(readFileSync(file, "utf8")), values, minLength);
  }
  return values;
}

// One loader, two floors (PAD-322, agreed with the PAD-320 owner): the text scan
// keeps the 3-character floor its backlog was seeded with; the role-name and
// alternation scans use 2, so "No"/"Não" count there without moving the text counts.
const locales: Locales = { en: loadLocale("en", 3), pt: loadLocale("pt", 3) };
const localesShort: Locales = { en: loadLocale("en", 2), pt: loadLocale("pt", 2) };
const playwrightFiles = walk(E2E_DIR, ".ts");
const maestroFiles = walk(MAESTRO_DIR, ".yaml");

const violations: Violation[] = [
  ...playwrightFiles.flatMap((f) =>
    scanPlaywright(`pw:${relative(E2E_DIR, f)}`, readFileSync(f, "utf8"), locales),
  ),
  ...maestroFiles.flatMap((f) =>
    scanMaestro(`mz:${relative(MAESTRO_DIR, f)}`, readFileSync(f, "utf8"), locales),
  ),
];

const countsByFile = violations.reduce<Record<string, number>>((acc, v) => {
  acc[v.file] = (acc[v.file] ?? 0) + 1;
  return acc;
}, {});

// PAD-342: typed role names are a second debt with its own list, written by this
// same run (one instrument, two files) so a text-conversion slice and a role-name
// slice never edit the same line.
const roleViolations: Violation[] = playwrightFiles.flatMap((f) =>
  scanRoleNames(`pw:${relative(E2E_DIR, f)}`, readFileSync(f, "utf8"), localesShort),
);

// PAD-322: bilingual alternations with a locale half — the third list, same run.
const altViolations: Violation[] = playwrightFiles.flatMap((f) =>
  scanAlternations(`pw:${relative(E2E_DIR, f)}`, readFileSync(f, "utf8"), localesShort),
);
const altCountsByFile = altViolations.reduce<Record<string, number>>((acc, v) => {
  acc[v.file] = (acc[v.file] ?? 0) + 1;
  return acc;
}, {});
const roleCountsByFile = roleViolations.reduce<Record<string, number>>((acc, v) => {
  acc[v.file] = (acc[v.file] ?? 0) + 1;
  return acc;
}, {});

/**
 * ONE INSTRUMENT, NOT TWO.
 *
 * The backlog is written by this scan, never by a separate script. The first seed was
 * produced by a standalone recount that disagreed with this guard 4x, because it
 * classified regex literals only when they contained an alternation. A list and a check
 * that are generated by different code will eventually disagree, and the disagreement is
 * invisible until someone builds the second one.
 *
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * Regenerating is not a way to make a red go away — see the file's own header.
 */
function renderBacklog(): string {
  const entries = Object.entries(countsByFile).sort(
    ([aFile, aN], [bFile, bN]) => bN - aN || aFile.localeCompare(bFile),
  );
  const rows = entries.map(([file, n]) => {
    const mine = violations.filter((v) => v.file === file);
    const langs = [...new Set(mine.map((v) => v.bucket))].sort().join("+");
    const examples = [...new Set(mine.map((v) => v.literal))]
      .sort()
      .slice(0, 2)
      .map((e) => `'${e.replace(/'/g, "")}'`)
      .join(", ");
    return `  { file: ${JSON.stringify(file)}, max: ${n}, reason: ${JSON.stringify(
      `${n} ${langs} UI string${n === 1 ? "" : "s"}, e.g. ${examples}`,
    )} },`;
  });
  const total = entries.reduce((sum, [, n]) => sum + n, 0);
  return `/**
 * PAD-320 — the conversion backlog for the rendered-text guard.
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST.
 *
 * Every entry is a file that still asserts on rendered copy and has not been converted
 * yet. An entry is a debt with a number on it, not permission. Adding one is a decision
 * with a name on it — say so in the commit message — and it is never the way to make a
 * red go away.
 *
 * \`max\` is a ratchet and the guard enforces it in BOTH directions:
 *   more than \`max\`  -> a new rendered-text assertion was added; fix the assertion
 *   fewer than \`max\` -> lower \`max\` to the number the failure message gives you
 *   zero             -> delete the entry
 *
 * The downward direction is the one that matters: headroom left after a partial
 * conversion lets new violations back in under the old ceiling while the guard reports
 * success, which is how a ratchet dies.
 *
 * GENERATED BY THE GUARD ITSELF — never by hand, never by a separate script:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * ${total} assertions across ${entries.length} files. Out of scope by decision and absent
 * here: \`getByRole(…, { name })\` with a typed name (its own list, e2e-role-name-backlog.ts,
 * PAD-342), the bilingual \`/delete|eliminar/i\` alternation (PAD-322), files whose subject
 * IS the text (SUBJECT_ALLOWLIST), and literals matching no locale value (test-created data).
 */

export interface BacklogEntry {
  /** Display name: \`pw:<path under apps/web/e2e>\` or \`mz:<path under .maestro>\`. */
  file: string;
  /** Exact number of convertible assertions remaining in the file. */
  max: number;
  /** What is in there, so a reader sees the size of the debt without opening it. */
  reason: string;
}

export const BACKLOG: readonly BacklogEntry[] = [
${rows.join("\n")}
] as const;
`;
}

function renderRoleBacklog(): string {
  const entries = Object.entries(roleCountsByFile).sort(
    ([aFile, aN], [bFile, bN]) => bN - aN || aFile.localeCompare(bFile),
  );
  const rows = entries.map(([file, n]) => {
    const mine = roleViolations.filter((v) => v.file === file);
    const langs = [...new Set(mine.map((v) => v.bucket))].sort().join("+");
    const examples = [...new Set(mine.map((v) => v.literal))]
      .sort()
      .slice(0, 2)
      .map((e) => `'${e.replace(/'/g, "")}'`)
      .join(", ");
    return `  { file: ${JSON.stringify(file)}, max: ${n}, reason: ${JSON.stringify(
      `${n} ${langs} role name${n === 1 ? "" : "s"}, e.g. ${examples}`,
    )} },`;
  });
  const total = entries.reduce((sum, [, n]) => sum + n, 0);
  return `/**
 * PAD-342 — the conversion backlog for TYPED role names (R-013 as amended).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST — the same contract as
 * e2e-rendered-text-backlog.ts: \`max\` is a ratchet enforced in both directions, an
 * entry is a debt with a number on it, and adding one is never the way to make a red
 * go away. The fix is \`name: ui("<locale key>")\` from e2e/helpers/i18n.ts, which the
 * scanner cannot see because it is a call, not a literal.
 *
 * GENERATED BY THE GUARD ITSELF, in the same run that writes the text backlog:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * ${total} typed role names across ${entries.length} files. Absent here: names given as a
 * call or an identifier (resolved, or test data by construction), literals matching no
 * locale value, and bilingual alternations (PAD-322).
 */

export interface RoleBacklogEntry {
  /** Display name: \`pw:<path under apps/web/e2e>\`. */
  file: string;
  /** Exact number of typed role names remaining in the file. */
  max: number;
  /** What is in there. */
  reason: string;
}

export const ROLE_BACKLOG: readonly RoleBacklogEntry[] = [
${rows.join("\n")}
] as const;
`;
}

function renderAltBacklog(): string {
  const entries = Object.entries(altCountsByFile).sort(
    ([aFile, aN], [bFile, bN]) => bN - aN || aFile.localeCompare(bFile),
  );
  const rows = entries.map(([file, n]) => {
    const examples = [...new Set(altViolations.filter((v) => v.file === file).map((v) => v.literal))]
      .sort()
      .slice(0, 2)
      .map((e) => `/${e.replace(/'/g, "")}/`)
      .join(", ");
    return `  { file: ${JSON.stringify(file)}, max: ${n}, reason: ${JSON.stringify(
      `${n} bilingual alternation${n === 1 ? "" : "s"}, e.g. ${examples}`,
    )} },`;
  });
  const total = entries.reduce((sum, [, n]) => sum + n, 0);
  return `/**
 * PAD-322 — the conversion backlog for BILINGUAL ALTERNATIONS (\`/delete|eliminar/i\`).
 *
 * THIS LIST IS A BACKLOG, NOT AN ALLOWLIST — the same contract as the text and role
 * backlogs: \`max\` is a ratchet enforced in both directions, an entry is a debt with a
 * number on it, and adding one is never the way to make a red go away. An alternation
 * is counted when at least one half resolves to a locale value; the fix is the same
 * resolved shape as a role name — \`ui("<locale key>")\` from e2e/helpers/i18n.ts — which
 * the scanner cannot see because it is a call, not a literal.
 *
 * GENERATED BY THE GUARD ITSELF, in the same run that writes the other two lists:
 *   UPDATE_E2E_TEXT_BACKLOG=1 npx vitest run src/lib/e2e-rendered-text-assertions.test.ts
 *
 * ${total} bilingual alternations across ${entries.length} files. Absent here: an escaped
 * bar (\`\\|\`), alternations whose halves resolve to nothing, and subject files.
 */

export interface AltBacklogEntry {
  /** Display name: \`pw:<path under apps/web/e2e>\`. */
  file: string;
  /** Exact number of bilingual alternations remaining in the file. */
  max: number;
  /** What is in there. */
  reason: string;
}

export const ALT_BACKLOG: readonly AltBacklogEntry[] = [
${rows.join("\n")}
] as const;
`;
}

if (process.env.UPDATE_E2E_TEXT_BACKLOG === "1") {
  writeFileSync(resolve(HERE, "e2e-rendered-text-backlog.ts"), renderBacklog());
  writeFileSync(resolve(HERE, "e2e-role-name-backlog.ts"), renderRoleBacklog());
  writeFileSync(resolve(HERE, "e2e-bilingual-backlog.ts"), renderAltBacklog());
}

describe("the scanner catches things", () => {
  // Without this block the whole guard can pass by matching nothing at all.
  const fixture: Locales = {
    en: new Set(["edit", "delete player", "attendance saved"]),
    pt: new Set(["editar", "delete player", "presencas guardadas"]),
  };

  it("flags an English UI string, a Portuguese one, and one identical in both", () => {
    expect(classify("pw:x.spec.ts", "Edit", fixture)).toBe("en");
    expect(classify("pw:x.spec.ts", "Editar", fixture)).toBe("pt");
    expect(classify("pw:x.spec.ts", "Delete player", fixture)).toBe("both");
  });

  it("leaves test-created data, bilingual alternations and subject files alone", () => {
    expect(classify("pw:x.spec.ts", "E2E Student Two", fixture)).toBe("data");
    expect(classify("pw:x.spec.ts", "delete|eliminar", fixture, true)).toBe("bilingual");
    expect(classify("pw:i18n-fallback.spec.ts", "Edit", fixture)).toBe("subject");
    expect(classify("mz:flows/14-student-calendar.yaml", "Edit", fixture)).toBe("subject");
  });

  it("finds a real assertion in a Playwright spec and in a Maestro flow", () => {
    const spec = `await expect(page.getByText("Edit")).toBeVisible();`;
    expect(scanPlaywright("pw:x.spec.ts", spec, fixture)).toEqual([
      { file: "pw:x.spec.ts", literal: "Edit", bucket: "en" },
    ]);
    const flow = `- assertVisible: "Attendance saved"\n- assertVisible: "E2E Student Two"\n`;
    expect(scanMaestro("mz:y.yaml", flow, fixture)).toEqual([
      { file: "mz:y.yaml", literal: "Attendance saved", bucket: "en" },
    ]);
  });
});

describe("the role-name scan tells resolved from typed (PAD-342)", () => {
  const fixture: Locales = {
    en: new Set(["delete", "add blocker", "undo", "previous week"]),
    pt: new Set(["eliminar", "adicionar bloqueio", "anular", "semana anterior"]),
  };
  const F = "pw:x.spec.ts";

  it("flags a typed string name, a typed regex name, and a name on the next line", () => {
    const spec = [
      `page.getByRole("button", { name: "Delete" })`,
      `page.getByRole("button", { name: /add blocker/i })`,
      `page.getByRole("button", { name: /^(undo)$/i })`,
      `page.getByRole("button", {\n  name: "Eliminar",\n})`,
    ].join("\n");
    expect(scanRoleNames(F, spec, fixture).map((v) => [v.literal, v.bucket])).toEqual([
      ["Delete", "en"],
      ["Eliminar", "pt"],
      ["add blocker", "en"],
      ["undo", "en"],
    ]);
  });

  it("is blind to a resolved name, an identifier, test data and a bilingual alternation", () => {
    const spec = [
      `page.getByRole("button", { name: ui("calendar.detail.delete") })`,
      `page.getByRole("heading", { name: target.title })`,
      `page.getByRole("button", { name: "E2E Academy Class" })`,
      `page.getByRole("button", { name: /previous week|semana anterior/i })`,
    ].join("\n");
    expect(scanRoleNames(F, spec, fixture)).toEqual([]);
  });
});

describe("the alternation scan counts copy, not data (PAD-322)", () => {
  const fixture: Locales = {
    en: new Set(["delete", "no", "save changes", "error"]),
    pt: new Set(["eliminar", "não", "guardar alterações"]),
  };
  const F = "pw:x.spec.ts";

  it("counts an alternation with a locale half, in a text matcher and in a role name", () => {
    const spec = [
      `page.getByText(/delete|eliminar/i)`,
      `page.getByRole("button", { name: /^(no|não)$/i })`,
      `expect(x).toHaveText(/save changes|guardar altera/i)`,
      `page.getByText(/error|failed/i)`,
    ].join("\n");
    expect(scanAlternations(F, spec, fixture).map((v) => v.literal)).toEqual([
      "delete|eliminar",
      "^(no|não)$",
      "save changes|guardar altera",
      "error|failed",
    ]);
  });

  it("ignores an escaped bar, halves that resolve to nothing, and resolved names", () => {
    const spec = [
      String.raw`page.getByText(/I1\s*\|\s*Intermediate/)`,
      `page.getByText(/create.*invite|invite.*player/i)`,
      `page.getByRole("button", { name: ui("common.delete") })`,
      `page.getByText("delete")`,
    ].join("\n");
    expect(scanAlternations(F, spec, fixture)).toEqual([]);
  });

  it("the short locale set lets a two-letter value count for roles and alternations only", () => {
    const short = localeValues({ a: "No", b: "Yes" }, new Set(), 2);
    const long = localeValues({ a: "No", b: "Yes" }, new Set(), 3);
    expect([...short].sort()).toEqual(["no", "yes"]);
    expect([...long]).toEqual(["yes"]);
  });
});

describe("the scan reached the real trees", () => {
  // A wrong path makes every literal look like test data and the guard vacuously green.
  it("loaded both locales", () => {
    expect(locales.en.size).toBeGreaterThan(200);
    expect(locales.pt.size).toBeGreaterThan(200);
  });

  it("read both test trees", () => {
    expect(playwrightFiles.length).toBeGreaterThan(50);
    expect(maestroFiles.length).toBeGreaterThan(20);
  });
});

describe("no assertion matches on rendered copy", () => {
  const listed = new Set(BACKLOG.map((e) => e.file));

  it("adds no new file", () => {
    const added = Object.keys(countsByFile)
      .filter((f) => !listed.has(f))
      .sort();
    expect(
      added,
      `these files assert on rendered copy and are not in the backlog. Assert on a ` +
        `data-testid instead — do NOT add them to the backlog to make this pass:\n` +
        added.map((f) => `  ${f}: ${countsByFile[f]}`).join("\n"),
    ).toEqual([]);
  });

  it.each(BACKLOG)("$file is at or below its ratchet ($max)", ({ file, max }) => {
    const actual = countsByFile[file] ?? 0;
    if (actual > max) {
      throw new Error(
        `${file}: ${actual} rendered-text assertions, ratchet is ${max}. ` +
          `A new one was added. Assert on a data-testid instead of raising the ratchet.`,
      );
    }
    if (actual < max) {
      throw new Error(
        `${file}: ${actual} rendered-text assertions, ratchet still says ${max}. ` +
          (actual === 0
            ? `Delete this entry from BACKLOG.`
            : `Lower max to ${actual} in BACKLOG — leaving headroom lets new ones back in silently.`),
      );
    }
    expect(actual).toBe(max);
  });
});

describe("no role name is typed (PAD-342)", () => {
  const listed = new Set(ROLE_BACKLOG.map((e) => e.file));

  it("adds no new file", () => {
    const added = Object.keys(roleCountsByFile)
      .filter((f) => !listed.has(f))
      .sort();
    expect(
      added,
      `these files type a role's accessible name and are not in the role backlog. Use ` +
        `name: ui("<locale key>") from e2e/helpers/i18n.ts — do NOT add them to the backlog:\n` +
        added.map((f) => `  ${f}: ${roleCountsByFile[f]}`).join("\n"),
    ).toEqual([]);
  });

  it.each(ROLE_BACKLOG)("$file is at or below its ratchet ($max)", ({ file, max }) => {
    const actual = roleCountsByFile[file] ?? 0;
    if (actual > max) {
      throw new Error(
        `${file}: ${actual} typed role names, ratchet is ${max}. A new one was added. ` +
          `Resolve it with name: ui("<locale key>") instead of raising the ratchet.`,
      );
    }
    if (actual < max) {
      throw new Error(
        `${file}: ${actual} typed role names, ratchet still says ${max}. ` +
          (actual === 0
            ? `Delete this entry from ROLE_BACKLOG.`
            : `Lower max to ${actual} in ROLE_BACKLOG — leaving headroom lets new ones back in silently.`),
      );
    }
    expect(actual).toBe(max);
  });
});

describe("no bilingual alternation is left typed (PAD-322)", () => {
  const listed = new Set(ALT_BACKLOG.map((e) => e.file));

  it("adds no new file", () => {
    const added = Object.keys(altCountsByFile)
      .filter((f) => !listed.has(f))
      .sort();
    expect(
      added,
      `these files match a bilingual alternation with a locale half and are not in the ` +
        `alternation backlog. Use ui("<locale key>") from e2e/helpers/i18n.ts — do NOT add them:\n` +
        added.map((f) => `  ${f}: ${altCountsByFile[f]}`).join("\n"),
    ).toEqual([]);
  });

  it.each(ALT_BACKLOG)("$file is at or below its ratchet ($max)", ({ file, max }) => {
    const actual = altCountsByFile[file] ?? 0;
    if (actual > max) {
      throw new Error(
        `${file}: ${actual} bilingual alternations, ratchet is ${max}. A new one was added. ` +
          `Resolve it with ui("<locale key>") instead of raising the ratchet.`,
      );
    }
    if (actual < max) {
      throw new Error(
        `${file}: ${actual} bilingual alternations, ratchet still says ${max}. ` +
          (actual === 0
            ? `Delete this entry from ALT_BACKLOG.`
            : `Lower max to ${actual} in ALT_BACKLOG — leaving headroom lets new ones back in silently.`),
      );
    }
    expect(actual).toBe(max);
  });
});
